In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import _init_paths
import numpy as np

import os
import cv2

import argparse
from opts import opts
from detectors.detector_factory import detector_factory

import pycocotools.coco as coco
from pycocotools.cocoeval import COCOeval
import sys
import pickle

image_ext = ['jpg', 'jpeg', 'png', 'webp']
video_ext = ['mp4', 'mov', 'avi', 'mkv']
time_stats = ['tot', 'load', 'pre', 'net', 'dec', 'post', 'merge']

In [2]:
opt = opts().init()

Fix size testing.
training chunk_sizes: [32]
/data/yy/github/CenterNet/src/lib/../../data
The output will be saved to  /data/yy/github/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}


In [3]:
print(opt)

Namespace(K=100, aggr_weight=0.0, agnostic_ex=False, arch='dla_34', aug_ddd=0.5, aug_rot=0, batch_size=32, cat_spec_wh=False, center_thresh=0.1, chunk_sizes=[32], ct_nopt_weight=1, ct_pt_weight=1, data_dir='/data/yy/github/CenterNet/src/lib/../../data', dataset='coco', debug=0, debug_dir='/data/yy/github/CenterNet/src/lib/../../exp/ctdet/default/debug', debugger_theme='white', demo='/data/yy/github/CenterNet/images', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=32, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='/data/yy/github/CenterNet/src/lib/../../exp/ctdet', exp_id='default', fix_res=True, flip=0.5, flip_test=False, gpus=[0], gpus_str='0', grid_size=14, head_conv=256, heads={'hm': 80, 'wh': 2, 'reg': 2}, hide_data_time=False, hm_hp=True, hm_hp_weight=1, hm_weight=1, hp_weight=1, input_h=448, input_res=448, input_w=448, keep_res

In [4]:
opt.load_model = '../models/ctdet_coco_dla_2x.pth'
opt.demo = '../images'
opt.down_ratio = 4

In [5]:
def demo(opt):
  os.environ['CUDA_VISIBLE_DEVICES'] = '0'
  opt.device = 'cuda'
  opt.debug = max(opt.debug, 1)
  Detector = detector_factory[opt.task]
  detector = Detector(opt)
  print("opt.demo", opt.demo)

  if opt.demo == 'webcam' or \
    opt.demo[opt.demo.rfind('.') + 1:].lower() in video_ext:
    print("begin webcam")
    cam = cv2.VideoCapture(0 if opt.demo == 'webcam' else opt.demo)
    detector.pause = False
    while True:
        _, img = cam.read()
        cv2.imshow('input', img)
        ret = detector.run(img)
        time_str = ''
        for stat in time_stats:
          time_str = time_str + '{} {:.3f}s |'.format(stat, ret[stat])
        print(time_str)
        if cv2.waitKey(1) == 27:
            return  # esc to quit
  else:
    if os.path.isdir(opt.demo):
      image_names = []
      ls = os.listdir(opt.demo)
      for file_name in sorted(ls):
          ext = file_name[file_name.rfind('.') + 1:].lower()
          if ext in image_ext:
              image_names.append(os.path.join(opt.demo, file_name))
    else:
      image_names = [opt.demo]

    for (image_name) in image_names:
      print("begin detector run")
      print("detector", image_name)
      ret = detector.run(image_name)
      print("-------------")
      print("ret", ret.keys())
      print("-------------")
      print(ret['results'].keys())
      print("-------------")
      print(ret['results'][1])
      #img = cv2.imread(image_name)
    
      print("get run")
      time_str = ''
      for stat in time_stats:
        print("stat", stat)
        time_str = time_str + '{} {:.3f}s |'.format(stat, ret[stat])
      print(time_str)

In [6]:
demo(opt)

Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
Begin model eval
opt.demo ../images
begin detector run
detector ../images/16004479832_a748d55f21_k.jpg
--------------- x device ----------------- cuda:0
write not ipynb img
-------------
ret dict_keys(['results', 'tot', 'load', 'pre', 'net', 'dec', 'post', 'merge'])
-------------
dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])
-------------
[[ 1.72171158e+02 -7.92694449e-01  4.83481018e+02  5.10803070e+02
   8.02863896e-01]
 [ 7.49697571e+02 -1.23087443e-01  8.26308838e+02  1.27011780e+02
   5.69256008e-01]
 [ 8.44749939e+02  2.14861441e+00  8.95049377e+02  1.37380463e+02
   5.54202080e-01]
 [ 4.84347534e+02  1.38644826e+00  5.93566345e+02  2.006020

--------------- x device ----------------- cuda:0
write not ipynb img
-------------
ret dict_keys(['results', 'tot', 'load', 'pre', 'net', 'dec', 'post', 'merge'])
-------------
dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])
-------------
[[6.3107727e+02 2.7803467e+02 6.6187384e+02 3.4465781e+02 7.3032957e-01]
 [5.0550000e+02 2.7460794e+02 5.3487207e+02 3.5168744e+02 6.9376278e-01]
 [2.8927576e+02 2.6630142e+02 3.1362415e+02 3.3174387e+02 6.6425109e-01]
 [3.7004596e+02 2.7054099e+02 3.8910492e+02 3.2549554e+02 6.5581161e-01]
 [4.3117221e+02 2.6604343e+02 4.5550525e+02 3.2577142e+02 6.1703980e-01]
 [3.8962741e+02 2.6955283e+02 4.0650336e+02 3.1292313e+02 6.1593813e-01]
 [5.9644659e+02 2.7714551e+02 6.1434973e+02 3.2

--------------- x device ----------------- cuda:0
write not ipynb img
-------------
ret dict_keys(['results', 'tot', 'load', 'pre', 'net', 'dec', 'post', 'merge'])
-------------
dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])
-------------
[[ 1.44845474e+02  3.66973999e+02  1.63954697e+02  4.14338806e+02
   2.29497850e-01]
 [ 4.36004791e+01  3.68767303e+02  5.51230736e+01  3.81218384e+02
   1.13159820e-01]
 [ 1.32696736e+00  3.66622101e+02  2.20630684e+01  3.88421478e+02
   7.89328218e-02]
 [ 3.83004456e+02  3.63722961e+02  4.28900818e+02  3.87214844e+02
   7.39024058e-02]
 [ 7.32766647e+01  3.72187164e+02  8.36075211e+01  3.93549561e+02
   4.60895523e-02]
 [ 3.72356110e+02  3.62159454e+02  3.90898376e+02  3.8963372

In [7]:
   
      for k in range(len(dets)):
      pred_ids = dets[k].getAnnIds(imgIds=[img_id])
      preds = dets[k].loadAnns(pred_ids)
      pred_img = cv2.imread(image_name)
      for j, pred in enumerate(ret['results']):
        bbox = _coco_box_to_bbox(pred['bbox'])
        sc = pred['score']
        cat_id = pred['category_id']
        if sc > 0.2:
          pred_img = add_box(img, bbox, sc, cat_id)
      #cv2.imshow('pred{}'.format(k), pred_img)
      cv2.imwrite('vis/{}_pred{}.png'.format(i, k), pred_img)
      cv2.imshow('input', ret['results'])

IndentationError: expected an indented block (<ipython-input-7-13b4788cfc00>, line 2)

In [ ]:
IMG_PATH = '../data/coco/val2017/'
ANN_PATH = '../data/coco/annotations/instances_val2017.json'
DEBUG = True

def _coco_box_to_bbox(box):
    bbox = np.array([box[0], box[1], box[0] + box[2], box[1] + box[3]],
                  dtype=np.int32)
    return bbox

_cat_ids = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 
  14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 
  24, 25, 27, 28, 31, 32, 33, 34, 35, 36, 
  37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 
  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 
  58, 59, 60, 61, 62, 63, 64, 65, 67, 70, 
  72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 
  82, 84, 85, 86, 87, 88, 89, 90
]
num_classes = 80
_classes = {
  ind + 1: cat_id for ind, cat_id in enumerate(_cat_ids)
}
_to_order = {cat_id: ind for ind, cat_id in enumerate(_cat_ids)}
coco = coco.COCO(ANN_PATH)
CAT_NAMES = [coco.loadCats([_classes[i + 1]])[0]['name'] \
              for i in range(num_classes)]
COLORS = [((np.random.random((3, )) * 0.6 + 0.4)*255).astype(np.uint8) \
              for _ in range(num_classes)]


def add_box(image, bbox, sc, cat_id):
    cat_id = _to_order[cat_id]
    cat_name = CAT_NAMES[cat_id]
    cat_size  = cv2.getTextSize(cat_name + '0', cv2.FONT_HERSHEY_SIMPLEX, 0.5, 2)[0]
    color = np.array(COLORS[cat_id]).astype(np.int32).tolist()
    txt = '{}{:.0f}'.format(cat_name, sc * 10)
    if bbox[1] - cat_size[1] - 2 < 0:
        cv2.rectangle(image,
                      (bbox[0], bbox[1] + 2),
                      (bbox[0] + cat_size[0], bbox[1] + cat_size[1] + 2),
                      color, -1)
        cv2.putText(image, txt, 
                    (bbox[0], bbox[1] + cat_size[1] + 2), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), thickness=1)
    else:
        cv2.rectangle(image,
                      (bbox[0], bbox[1] - cat_size[1] - 2),
                      (bbox[0] + cat_size[0], bbox[1] - 2),
                      color, -1)
        cv2.putText(image, txt, 
                    (bbox[0], bbox[1] - 2), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), thickness=1)
        cv2.rectangle(image,
                    (bbox[0], bbox[1]),
                    (bbox[2], bbox[3]),
                    color, 2)
    return image

dets = []
img_ids = coco.getImgIds()
num_images = len(img_ids)
for k in range(1, len(sys.argv)):
    pred_path = sys.argv[k]
    dets.append(coco.loadRes(pred_path))
# import pdb; pdb.set_trace()
for i, img_id in enumerate(img_ids):
    img_info = coco.loadImgs(ids=[img_id])[0]
    img_path = IMG_PATH + img_info['file_name']
    img = cv2.imread(img_path)
    gt_ids = coco.getAnnIds(imgIds=[img_id])
    gts = coco.loadAnns(gt_ids)
    gt_img = img.copy()
    for j, pred in enumerate(gts):
        bbox = _coco_box_to_bbox(pred['bbox'])
        cat_id = pred['category_id']
        gt_img = add_box(gt_img, bbox, 0, cat_id)
    for k in range(len(dets)):
        pred_ids = dets[k].getAnnIds(imgIds=[img_id])
        preds = dets[k].loadAnns(pred_ids)
        pred_img = img.copy()
        for j, pred in enumerate(preds):
            bbox = _coco_box_to_bbox(pred['bbox'])
            sc = pred['score']
            cat_id = pred['category_id']
        if sc > 0.2:
            pred_img = add_box(pred_img, bbox, sc, cat_id)
        cv2.imshow('pred{}'.format(k), pred_img)
      # cv2.imwrite('vis/{}_pred{}.png'.format(i, k), pred_img)
    cv2.imshow('gt', gt_img)
    # cv2.imwrite('vis/{}_gt.png'.format(i), gt_img)
    cv2.waitKey()
  # coco_eval.evaluate()
  # coco_eval.accumulate()
  # coco_eval.summarize()
